version: "2"
exclude_patterns:
  - "migrations/"
  - "tests/"
checks:
  method-complexity:
    config:
      threshold: 10
  # Don't complain if files are too long
  file-lines:
    enabled: false
config:
  languages:
    python:
      python_version: 3
