version: "2"
exclude_patterns:
  - "migrations/"
  - "tests/"
checks:
  method-complexity:
    config:
      threshold: 10
  argument-count:
    config:
      threshold: 6
  # Don't complain if files are too long
  file-lines:
    enabled: false
