language: "python"
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  global:
    - PYTHONPATH=$PYTHONPATH:$(pwd)/cidc_api
    - GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json
install:
  - pip install -r requirements.txt -r requirements.dev.txt
before_script:
  - psql -c "create user cidcdev with password '1234'"
  - psql -c "create database cidctest"
  - psql -c "grant all privileges on database cidctest to cidcdev"
script:
  - pytest
  - black --check cidc_api --target-version=py36

before_deploy:
  - if [ "$TRAVIS_BRANCH" = production ]; then
      echo "$GCLOUD_SERVICE_ACCOUNT_JSON_PROD" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS;
    else
      echo "$GCLOUD_SERVICE_ACCOUNT_JSON_STAGING" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS;
    fi
deploy:
  - provider: gae
    keyfile: $GOOGLE_APPLICATION_CREDENTIALS
    project: cidc-dfci-staging
    config: app.staging.yaml
    on:
      branch: master
  - provider: gae
    keyfile: $GOOGLE_APPLICATION_CREDENTIALS
    project: cidc-dfci
    config: app.prod.yaml
    on:
      branch: production
