"""empty message

Revision ID: 2b11e3ecbe93
Revises: 37888cac6b2b
Create Date: 2019-07-16 15:50:45.555758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b11e3ecbe93'
down_revision = '37888cac6b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_jobs',
    sa.Column('_created', sa.DateTime(), nullable=True),
    sa.Column('_updated', sa.DateTime(), nullable=True),
    sa.Column('_etag', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('started', 'completed', 'errored', name='job_statuses'), nullable=False),
    sa.Column('gcs_objects', postgresql.ARRAY(sa.String(), dimensions=1), nullable=False),
    sa.Column('metadata_json_patch', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('xlsx_bytes', postgresql.BYTEA(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('gcs_objects_idx', 'upload_jobs', ['gcs_objects'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('gcs_objects_idx', table_name='upload_jobs')
    op.drop_table('upload_jobs')
    # ### end Alembic commands ###
