"""empty message

Revision ID: f33a15cb6cda
Revises: 7df49a8d4792
Create Date: 2019-08-14 14:01:47.856773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33a15cb6cda'
down_revision = '7df49a8d4792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloadable_files',
    sa.Column('_created', sa.DateTime(), nullable=True),
    sa.Column('_updated', sa.DateTime(), nullable=True),
    sa.Column('_etag', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('gs_uri', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trial_metadata.trial_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_table('downloadable_files')
    # ### end Alembic commands ###
