name: Create Prod release PR

on:
  schedule:
  - cron: "5 11,18 * * 1-5" #it's 7:05am and 2:05pm EDT

jobs:
  build:
    name: Create Prod release PR
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout master
      #  uses: actions/checkout@master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          base: production
          # defaults to commit message if empty
          title: "Prod release"
 
